execution:
  geth:
    name: ethereum/client-go
    version: v1.14.3
  besu:
    name: hyperledger/besu
    version: 24.5.2
  nethermind:
    name: nethermind/nethermind
    version: 1.26.0
  erigon:
    name: thorax/erigon
    version: v2.60.0
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v5.1.3
  lodestar:
    name: chainsafe/lodestar
    version: v1.18.1
  teku:
    name: consensys/teku
    version: 24.4.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v5.0.3
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v5.1.3
  lodestar:
    name: chainsafe/lodestar
    version: v1.18.1
  teku:
    name: consensys/teku
    version: 24.4.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v5.0.3
